export const notificationBooleanKeys = [
  "telegram_enabled",
  "practice_reminders",
  "qualifying_reminders",
  "sprint_reminders",
  "race_reminders",
  "reminder_24h",
  "reminder_1h",
  "reminder_15m",
  "schedule_changes",
  "practice_results",
  "qualifying_results",
  "sprint_results",
  "race_results",
  "fantasy_opened",
  "fantasy_incomplete",
  "fantasy_deadlines",
  "fantasy_locked",
  "fantasy_scored",
  "fantasy_rank_changes",
  "important_news",
  "favorite_driver_news",
  "favorite_team_news",
  "transfer_news",
  "steward_news",
  "technical_news",
  "daily_digest",
  "weather_changes",
  "rain_alerts",
  "extreme_heat_alerts",
  "possible_session_delay",
  "championship_updates",
] as const;

export type NotificationBooleanKey = (typeof notificationBooleanKeys)[number];

export type NotificationPreferences = Record<NotificationBooleanKey, boolean> & {
  quiet_hours_start: string | null;
  quiet_hours_end: string | null;
  delivery_mode: "instant" | "digest";
};

export const defaultNotificationPreferences: NotificationPreferences = {
  telegram_enabled: true,
  practice_reminders: false,
  qualifying_reminders: true,
  sprint_reminders: true,
  race_reminders: true,
  reminder_24h: false,
  reminder_1h: true,
  reminder_15m: true,
  schedule_changes: true,
  practice_results: true,
  qualifying_results: true,
  sprint_results: true,
  race_results: true,
  fantasy_opened: true,
  fantasy_incomplete: true,
  fantasy_deadlines: true,
  fantasy_locked: false,
  fantasy_scored: true,
  fantasy_rank_changes: true,
  important_news: true,
  favorite_driver_news: false,
  favorite_team_news: false,
  transfer_news: false,
  steward_news: true,
  technical_news: false,
  daily_digest: false,
  weather_changes: true,
  rain_alerts: true,
  extreme_heat_alerts: true,
  possible_session_delay: true,
  championship_updates: true,
  quiet_hours_start: null,
  quiet_hours_end: null,
  delivery_mode: "instant",
};
