import {
  Activity,
  AlertTriangle,
  Bell,
  Bot,
  ClipboardList,
  Clock3,
  CreditCard,
  FileText,
  Gauge,
  MessageSquareWarning,
  Newspaper,
  Radio,
  ScrollText,
  ServerCog,
  ShieldCheck,
  Trophy,
} from "lucide-react";

export const adminNavigation = [
  { href: "/admin", label: "Обзор", icon: Gauge, group: "Контроль" },
  { href: "/admin/findings", label: "Проблемы и проверки", icon: AlertTriangle, group: "Контроль" },
  { href: "/admin/systems", label: "Системы", icon: ServerCog, group: "Контроль" },
  { href: "/admin/jobs", label: "Задачи", icon: ClipboardList, group: "Контроль" },
  { href: "/admin/schedules", label: "Расписания", icon: Clock3, group: "Контроль" },
  { href: "/admin/news", label: "Новости", icon: Newspaper, group: "Контент" },
  { href: "/admin/social", label: "Соцсети", icon: Radio, group: "Контент" },
  { href: "/admin/reports", label: "Отчёты", icon: FileText, group: "Контент" },
  { href: "/admin/issues", label: "Сообщения читателей", icon: MessageSquareWarning, group: "Контент" },
  { href: "/admin/sport", label: "Спорт", icon: Trophy, group: "Спорт и сообщество" },
  { href: "/admin/community", label: "Сообщество", icon: Activity, group: "Спорт и сообщество" },
  { href: "/admin/users", label: "Пользователи", icon: ShieldCheck, group: "Пользователи" },
  { href: "/admin/notifications", label: "Уведомления", icon: Bell, group: "Пользователи" },
  { href: "/admin/billing", label: "Подписки и оплаты", icon: CreditCard, group: "Пользователи" },
  { href: "/admin/ai", label: "AI и бюджет", icon: Bot, group: "Настройки" },
  { href: "/admin/audit", label: "Аудит", icon: ScrollText, group: "Настройки" },
] as const;
