export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type TableDefinition<Row, Insert = Partial<Row>, Update = Partial<Insert>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: never[];
};

export type Database = {
  public: {
    Tables: {
      profiles: TableDefinition<{
        id: string;
        email: string | null;
        display_name: string | null;
        language: string;
        timezone: string;
        onboarding_completed: boolean;
        created_at: string;
        updated_at: string;
      }>;
      telegram_accounts: TableDefinition<{
        user_id: string;
        telegram_user_id: number;
        chat_id: number;
        username: string | null;
        first_name: string | null;
        is_active: boolean;
        connected_at: string;
        disconnected_at: string | null;
        last_delivery_at: string | null;
        last_error: string | null;
        updated_at: string;
      }>;
      telegram_link_tokens: TableDefinition<{
        id: string;
        user_id: string;
        token_hash: string;
        expires_at: string;
        used_at: string | null;
        created_at: string;
      }>;
      notification_preferences: TableDefinition<{
        user_id: string;
        telegram_enabled: boolean;
        practice_reminders: boolean;
        qualifying_reminders: boolean;
        sprint_reminders: boolean;
        race_reminders: boolean;
        reminder_24h: boolean;
        reminder_1h: boolean;
        reminder_15m: boolean;
        schedule_changes: boolean;
        practice_results: boolean;
        qualifying_results: boolean;
        sprint_results: boolean;
        race_results: boolean;
        fantasy_opened: boolean;
        fantasy_incomplete: boolean;
        fantasy_deadlines: boolean;
        fantasy_locked: boolean;
        fantasy_scored: boolean;
        fantasy_rank_changes: boolean;
        important_news: boolean;
        favorite_driver_news: boolean;
        favorite_team_news: boolean;
        transfer_news: boolean;
        steward_news: boolean;
        technical_news: boolean;
        daily_digest: boolean;
        weather_changes: boolean;
        rain_alerts: boolean;
        extreme_heat_alerts: boolean;
        possible_session_delay: boolean;
        championship_updates: boolean;
        session_notifications: Json;
        quiet_hours_start: string | null;
        quiet_hours_end: string | null;
        delivery_mode: string;
        updated_at: string;
      }>;
      spoiler_reveals: TableDefinition<{
        user_id: string;
        session_id: string;
        revealed_at: string;
      }>;
      notification_queue: TableDefinition<{
        id: string;
        user_id: string;
        event_type: string;
        entity_type: string | null;
        entity_id: string | null;
        payload: Json;
        available_at: string;
        status: string;
        dedupe_key: string;
        attempts: number;
        last_error: string | null;
        created_at: string;
        sent_at: string | null;
      }>;
      notification_logs: TableDefinition<{
        id: string;
        queue_id: string | null;
        user_id: string;
        channel: string;
        event_type: string;
        status: string;
        provider_message_id: string | null;
        error_message: string | null;
        created_at: string;
      }>;
      admin_users: TableDefinition<{
        user_id: string;
        created_at: string;
      }>;
      teams: TableDefinition<{
        id: string;
        external_id: string | null;
        code: string;
        name: string;
        short_name: string | null;
        country: string | null;
        color_hex: string | null;
        badge_variant: string | null;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      }>;
      drivers: TableDefinition<{
        id: string;
        external_id: string | null;
        slug: string | null;
        code: string | null;
        permanent_number: number | null;
        first_name: string;
        last_name: string;
        full_name: string;
        country: string | null;
        country_code: string | null;
        current_team_id: string | null;
        avatar_style_key: string | null;
        ai_avatar_url: string | null;
        avatar_placeholder_style: string | null;
        is_active: boolean;
        created_at: string;
        updated_at: string;
      }>;
      circuits: TableDefinition<{
        id: string;
        external_id: string | null;
        slug: string | null;
        name: string;
        country: string | null;
        locality: string | null;
        latitude: number | null;
        longitude: number | null;
        timezone: string | null;
        lap_length_km: number | null;
        race_laps: number | null;
        race_distance_km: number | null;
        turns_count: number | null;
        direction: string | null;
        first_grand_prix_year: number | null;
        lap_record_time: string | null;
        lap_record_driver: string | null;
        lap_record_year: number | null;
        drs_zones_count: number | null;
        track_type: string | null;
        track_description: string | null;
        overtaking_rating: number | null;
        qualifying_importance_rating: number | null;
        tyre_wear_rating: number | null;
        safety_car_rating: number | null;
        strategy_variability_rating: number | null;
        rain_risk_rating: number | null;
        created_at: string;
        updated_at: string;
      }>;
      circuit_grand_prix_history: TableDefinition<{
        id: string;
        circuit_id: string;
        season: number;
        round: number;
        race_id: string | null;
        race_name: string;
        race_date: string | null;
        winner_driver_id: string | null;
        winner_team_id: string | null;
        pole_driver_id: string | null;
        pole_team_id: string | null;
        winner_start_position: number | null;
        winner_from_pole: boolean | null;
        podium_json: Json;
        dnf_count: number | null;
        safety_car_count: number | null;
        vsc_count: number | null;
        red_flag_count: number | null;
        strategy_json: Json;
        raw_payload: Json;
        source_errors: Json;
        created_at: string;
        updated_at: string;
      }>;
      circuit_stats: TableDefinition<{
        id: string;
        circuit_id: string;
        calculated_from_season: number | null;
        calculated_to_season: number | null;
        races_count: number;
        pole_win_rate: number | null;
        front_row_win_rate: number | null;
        winner_avg_start_position: number | null;
        avg_position_delta: number | null;
        avg_abs_position_delta: number | null;
        best_position_gain_json: Json | null;
        worst_position_loss_json: Json | null;
        avg_dnf_count: number | null;
        avg_pit_stops: number | null;
        avg_first_pit_lap: number | null;
        most_common_strategy: string | null;
        strategy_distribution: Json;
        safety_car_frequency: number | null;
        vsc_frequency: number | null;
        red_flag_frequency: number | null;
        chaos_score: number | null;
        overtaking_level: string | null;
        qualifying_importance_level: string | null;
        strategy_variability_level: string | null;
        records_json: Json;
        ai_preview: string | null;
        ai_preview_status: string;
        ai_preview_generated_at: string | null;
        source_errors: Json;
        calculated_at: string;
        created_at: string;
        updated_at: string;
      }>;
      circuit_driver_stats: TableDefinition<{
        id: string;
        circuit_id: string;
        driver_id: string;
        season_scope: string;
        starts: number;
        wins: number;
        podiums: number;
        points_finishes: number;
        dnfs: number;
        avg_start_position: number | null;
        avg_finish_position: number | null;
        best_finish: number | null;
        best_start: number | null;
        avg_position_delta: number | null;
        total_position_delta: number;
        created_at: string;
        updated_at: string;
      }>;
      circuit_team_stats: TableDefinition<{
        id: string;
        circuit_id: string;
        team_id: string;
        season_scope: string;
        starts: number;
        wins: number;
        podiums: number;
        points_finishes: number;
        avg_points: number | null;
        best_finish: number | null;
        worst_finish: number | null;
        double_points_finishes: number;
        created_at: string;
        updated_at: string;
      }>;
      seasons: TableDefinition<{
        year: number;
        created_at: string;
      }>;
      news_sources: TableDefinition<{
        id: string;
        name: string;
        source_type: string;
        url: string;
        language: string | null;
        is_active: boolean;
        fetch_interval_minutes: number;
        last_fetched_at: string | null;
        last_success_at: string | null;
        last_error: string | null;
        created_at: string;
        updated_at: string;
      }>;
      news_articles: TableDefinition<{
        id: string;
        source_id: string | null;
        canonical_url: string;
        original_url: string | null;
        original_title: string;
        original_description: string | null;
        original_language: string | null;
        published_at: string | null;
        fetched_at: string;
        ai_summary_ru: string | null;
        ai_summary_long_ru: string | null;
        ai_key_points_ru: string[];
        ai_highlights_ru: string[];
        ai_title_ru: string | null;
        image_url: string | null;
        source_image_url: string | null;
        image_prompt: string | null;
        image_model: string | null;
        image_status: string;
        image_generated_at: string | null;
        image_metadata: Json;
        importance_score: number;
        status: string;
        duplicate_of: string | null;
        related_race_id: string | null;
        raw_payload: Json | null;
        ai_model: string | null;
        ai_processed_at: string | null;
        created_at: string;
        updated_at: string;
      }>;
      tags: TableDefinition<{
        id: string;
        type: string;
        slug: string;
        name: string;
        created_at: string;
      }>;
      news_article_tags: TableDefinition<{
        article_id: string;
        tag_id: string;
        confidence: number;
        method: string;
      }>;
      social_sources: TableDefinition<{
        id: string;
        platform: string;
        name: string;
        source_type: string;
        url: string;
        adapter: string;
        feed_kind: string | null;
        is_active: boolean;
        fetch_interval_minutes: number;
        last_fetched_at: string | null;
        last_success_at: string | null;
        last_error: string | null;
        external_key: string | null;
        trust_level: string;
        publication_mode: string;
        initial_backfill_days: number;
        cursor: string | null;
        last_seen_external_id: string | null;
        include_reposts: boolean;
        include_replies: boolean;
        next_fetch_at: string | null;
        rate_limited_until: string | null;
        metadata: Json;
        created_at: string;
        updated_at: string;
      }>;
      social_posts: TableDefinition<{
        id: string;
        platform: string;
        source_id: string | null;
        external_id: string;
        author: string | null;
        title: string | null;
        body: string | null;
        original_url: string;
        image_url: string | null;
        published_at: string | null;
        reaction_count: number | null;
        popularity_score: number;
        raw_payload: Json | null;
        status: string;
        original_language: string | null;
        ai_title_ru: string | null;
        ai_summary_ru: string | null;
        content_kind: string | null;
        importance_score: number;
        relevance_score: number | null;
        ai_confidence: number | null;
        ai_model: string | null;
        ai_processed_at: string | null;
        processing_attempts: number;
        next_retry_at: string | null;
        last_processing_error: string | null;
        duplicate_of: string | null;
        content_hash: string | null;
        source_metrics: Json;
        comments_count: number | null;
        repost_count: number | null;
        view_count: number | null;
        edited_at: string | null;
        last_synced_at: string;
        created_at: string;
        updated_at: string;
      }>;
      social_post_tags: TableDefinition<{
        post_id: string;
        tag_id: string;
        confidence: number;
        method: string;
        is_primary: boolean;
        created_at: string;
      }>;
      social_post_media: TableDefinition<{
        id: string;
        post_id: string;
        media_type: string;
        url: string;
        preview_url: string | null;
        alt_text: string | null;
        width: number | null;
        height: number | null;
        sort_order: number;
        provider_media_id: string | null;
        created_at: string;
      }>;
      grand_prix_reports: TableDefinition<{
        id: string;
        season: number;
        round: number;
        race_slug: string;
        race_name: string;
        circuit_name: string | null;
        country: string | null;
        race_date: string | null;
        status: string;
        is_hidden: boolean;
        source_updated_at: string | null;
        generated_at: string | null;
        summary_status: string;
        ai_summary: string | null;
        weather: Json;
        race_statistics: Json;
        results: Json;
        key_events: Json;
        pit_stops: Json;
        strategies: Json;
        teammate_comparisons: Json;
        highlights: Json;
        championship_impact: Json;
        news_summary: Json;
        source_errors: Json;
        last_error: string | null;
        refresh_stage: number;
        next_refresh_at: string | null;
        structured_hash: string | null;
        created_at: string;
        updated_at: string;
      }>;
      article_reactions: TableDefinition<{
        article_id: string;
        user_id: string;
        reaction: string;
        created_at: string;
      }>;
      user_favorite_teams: TableDefinition<{
        user_id: string;
        team_id: string;
        created_at: string;
      }>;
      user_favorite_drivers: TableDefinition<{
        user_id: string;
        driver_id: string;
        created_at: string;
      }>;
      races: TableDefinition<{
        id: string;
        season_year: number;
        round: number;
        race_name: string;
        circuit_id: string | null;
        official_url: string | null;
        race_start_at: string | null;
        status: string;
        created_at: string;
        updated_at: string;
      }>;
      sessions: TableDefinition<{
        id: string;
        race_id: string;
        session_type: string;
        name: string;
        start_at: string | null;
        end_at: string | null;
        status: string;
        openf1_session_key: number | null;
        created_at: string;
        updated_at: string;
      }>;
      driver_standings: TableDefinition<{
        id: string;
        season_year: number;
        round: number | null;
        driver_id: string;
        team_id: string | null;
        position: number | null;
        points: number;
        wins: number;
        raw_payload: Json | null;
        updated_at: string;
      }>;
      constructor_standings: TableDefinition<{
        id: string;
        season_year: number;
        round: number | null;
        team_id: string;
        position: number | null;
        points: number;
        wins: number;
        raw_payload: Json | null;
        updated_at: string;
      }>;
      session_results: TableDefinition<{
        id: string;
        session_id: string;
        driver_id: string | null;
        team_id: string | null;
        position: number | null;
        classified_position: string | null;
        grid: number | null;
        laps: number | null;
        points: number | null;
        status: string | null;
        time_text: string | null;
        raw_payload: Json | null;
        created_at: string;
        updated_at: string;
      }>;
      circuit_weather: TableDefinition<{
        id: string;
        race_id: string | null;
        circuit_id: string | null;
        temperature_c: number | null;
        wind_speed_kmh: number | null;
        precipitation_mm: number | null;
        weather_code: number | null;
        observed_at: string | null;
        provider: string;
        raw_payload: Json | null;
        created_at: string;
        updated_at: string;
      }>;
      circuit_layouts: TableDefinition<{
        id: string;
        circuit_id: string;
        provider: string;
        svg_path: string;
        view_box: string;
        source_session_key: number | null;
        raw_payload: Json | null;
        created_at: string;
        updated_at: string;
      }>;
      track_maps: TableDefinition<{
        id: string;
        circuit_id: string | null;
        circuit_key: string;
        circuit_name: string;
        season_source: number;
        meeting_key: number | null;
        session_key: number | null;
        definition: Json;
        created_at: string;
        updated_at: string;
      }>;
      race_replay_sessions: TableDefinition<{
        id: string;
        race_id: string | null;
        circuit_id: string | null;
        track_map_id: string | null;
        title: string;
        status: string;
        source_season: number;
        source_meeting_key: number | null;
        source_session_key: number;
        source_session_name: string | null;
        source_race_name: string | null;
        source_started_at: string | null;
        duration_ms: number | null;
        total_laps: number | null;
        snapshot: Json;
        source_errors: Json;
        prepared_at: string | null;
        created_at: string;
        updated_at: string;
      }>;
      race_replay_events: TableDefinition<{
        id: string;
        replay_session_id: string;
        event_time: string;
        offset_ms: number;
        event_type: string;
        driver_number: number | null;
        payload: Json;
        created_at: string;
      }>;
      session_weather: TableDefinition<{
        id: string;
        session_id: string;
        race_id: string | null;
        circuit_id: string | null;
        temperature_c: number | null;
        wind_speed_kmh: number | null;
        precipitation_mm: number | null;
        weather_code: number | null;
        forecast_at: string | null;
        provider: string;
        raw_payload: Json | null;
        created_at: string;
        updated_at: string;
      }>;
      prediction_leagues: TableDefinition<{
        id: string;
        owner_user_id: string;
        name: string;
        invite_code: string;
        is_public: boolean;
        created_at: string;
        updated_at: string;
      }>;
      prediction_league_members: TableDefinition<{
        league_id: string;
        user_id: string;
        role: string;
        joined_at: string;
      }>;
      predictions: TableDefinition<{
        id: string;
        user_id: string;
        race_id: string;
        league_id: string | null;
        pole_driver_id: string | null;
        winner_driver_id: string | null;
        fastest_lap_driver_id: string | null;
        dnf_driver_id: string | null;
        dnf_pick_kind: string;
        top_scoring_team_id: string | null;
        fastest_pit_stop_team_id: string | null;
        top3_driver_ids: string[] | null;
        top10_driver_ids: string[] | null;
        submitted_at: string;
        locked_at: string | null;
        score: number | null;
        score_breakdown: Json | null;
        scored_at: string | null;
        is_public: boolean;
        share_slug: string | null;
        shared_at: string | null;
        share_image_version: number;
      }>;
      polls: TableDefinition<{
        id: string;
        race_id: string | null;
        question: string;
        status: string;
        closes_at: string | null;
        poll_kind: string | null;
        generated_by_ai: boolean;
        generated_at: string | null;
        created_at: string;
        updated_at: string;
      }>;
      poll_options: TableDefinition<{
        id: string;
        poll_id: string;
        label: string;
        sort_order: number;
      }>;
      poll_votes: TableDefinition<{
        poll_id: string;
        option_id: string;
        user_id: string;
        created_at: string;
      }>;
      digests: TableDefinition<{
        id: string;
        digest_type: string;
        date_key: string | null;
        race_id: string | null;
        title: string;
        body_md: string;
        ai_model: string | null;
        generated_at: string;
        status: string;
      }>;
      job_runs: TableDefinition<{
        id: string;
        job_name: string;
        status: string;
        started_at: string;
        finished_at: string | null;
        items_processed: number;
        error_message: string | null;
        metadata: Json | null;
      }>;
      ai_usage_logs: TableDefinition<{
        id: string;
        purpose: string;
        provider: string;
        model: string;
        input_tokens: number | null;
        output_tokens: number | null;
        estimated_cost_usd: number | null;
        related_article_id: string | null;
        related_digest_id: string | null;
        created_at: string;
      }>;
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: never;
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
