alter table public.news_articles
  add column if not exists source_published_at timestamptz,
  add column if not exists rss_guid text,
  add column if not exists normalized_source_url text,
  add column if not exists source_content_hash text,
  add column if not exists main_fact text,
  add column if not exists event_type text,
  add column if not exists event_stage text,
  add column if not exists event_date date,
  add column if not exists event_fingerprint text,
  add column if not exists normalized_entities jsonb not null default '[]'::jsonb,
  add column if not exists ingested_at timestamptz not null default now(),
  add column if not exists dedup_checked_at timestamptz,
  add column if not exists dedup_status text not null default 'pending',
  add column if not exists publication_status text not null default 'processing',
  add column if not exists duplicate_confidence numeric(5, 4),
  add column if not exists duplicate_relation text,
  add column if not exists duplicate_reason text,
  add column if not exists dedup_candidate_count integer not null default 0,
  add column if not exists dedup_processing_time_ms integer,
  add column if not exists dedup_decision_history jsonb not null default '[]'::jsonb,
  add column if not exists published_manually boolean not null default false,
  add column if not exists manual_published_at timestamptz,
  add column if not exists manual_published_by uuid references auth.users(id) on delete set null;

update public.news_articles
set
  source_published_at = coalesce(source_published_at, published_at),
  normalized_source_url = coalesce(normalized_source_url, canonical_url),
  ingested_at = coalesce(fetched_at, created_at, now()),
  dedup_status = case
    when duplicate_of is not null then 'duplicate'
    else 'skipped'
  end,
  publication_status = case
    when duplicate_of is not null then 'duplicate'
    when status = 'processed' then 'published'
    when status = 'failed' then 'failed'
    else 'processing'
  end;

alter table public.news_articles
  drop constraint if exists news_articles_dedup_status_check,
  add constraint news_articles_dedup_status_check
    check (dedup_status in ('pending', 'checking', 'unique', 'duplicate', 'error', 'skipped')),
  drop constraint if exists news_articles_publication_status_check,
  add constraint news_articles_publication_status_check
    check (publication_status in ('processing', 'processing_dedup', 'published', 'duplicate', 'failed', 'rejected', 'draft')),
  drop constraint if exists news_articles_duplicate_confidence_check,
  add constraint news_articles_duplicate_confidence_check
    check (duplicate_confidence is null or duplicate_confidence between 0 and 1),
  drop constraint if exists news_articles_duplicate_relation_check,
  add constraint news_articles_duplicate_relation_check
    check (
      duplicate_relation is null
      or duplicate_relation in (
        'duplicate',
        'update',
        'official_confirmation',
        'decision',
        'result',
        'analysis',
        'reaction',
        'related',
        'unrelated'
      )
    ),
  drop constraint if exists news_articles_normalized_entities_array_check,
  add constraint news_articles_normalized_entities_array_check
    check (jsonb_typeof(normalized_entities) = 'array');

create index if not exists news_articles_publication_status_ingested_idx
  on public.news_articles (publication_status, ingested_at desc);
create index if not exists news_articles_event_fingerprint_ingested_idx
  on public.news_articles (event_fingerprint, ingested_at desc)
  where event_fingerprint is not null;
create index if not exists news_articles_normalized_source_url_idx
  on public.news_articles (normalized_source_url)
  where normalized_source_url is not null;
create index if not exists news_articles_source_content_hash_idx
  on public.news_articles (source_content_hash)
  where source_content_hash is not null;
create index if not exists news_articles_rss_guid_source_idx
  on public.news_articles (source_id, rss_guid)
  where rss_guid is not null;
create index if not exists news_articles_normalized_entities_gin_idx
  on public.news_articles using gin (normalized_entities);

create table if not exists public.news_dedup_locks (
  lock_key text primary key,
  article_id uuid not null references public.news_articles(id) on delete cascade,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists news_dedup_locks_expires_at_idx
  on public.news_dedup_locks (expires_at);

create table if not exists public.news_dedup_decisions (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.news_articles(id) on delete cascade,
  duplicate_of uuid references public.news_articles(id) on delete set null,
  candidate_count integer not null default 0,
  is_duplicate boolean not null default false,
  confidence numeric(5, 4),
  relation text,
  reason text,
  dedup_status text not null,
  publication_status text not null,
  processing_time_ms integer,
  error_message text,
  decision_source text not null default 'pipeline',
  created_at timestamptz not null default now(),
  constraint news_dedup_decisions_confidence_check
    check (confidence is null or confidence between 0 and 1),
  constraint news_dedup_decisions_relation_check
    check (
      relation is null
      or relation in (
        'duplicate',
        'update',
        'official_confirmation',
        'decision',
        'result',
        'analysis',
        'reaction',
        'related',
        'unrelated'
      )
    ),
  constraint news_dedup_decisions_source_check
    check (decision_source in ('pipeline', 'technical', 'audit', 'manual_override'))
);

create index if not exists news_dedup_decisions_article_created_idx
  on public.news_dedup_decisions (article_id, created_at desc);
create index if not exists news_dedup_decisions_duplicate_of_idx
  on public.news_dedup_decisions (duplicate_of)
  where duplicate_of is not null;

do $$
begin
  if to_regclass('public.news_story_articles') is not null
    and to_regclass('public.news_stories') is not null then
    execute $view$
      create or replace view public.news_feed_entries
      with (security_invoker = true)
      as
      select 'article'::text as entry_kind, articles.id as entry_id, articles.published_at
      from public.news_articles articles
      where articles.status = 'processed'
        and articles.publication_status = 'published'
        and articles.duplicate_of is null
        and (articles.ai_model is null or articles.ai_model <> 'fallback')
        and not exists (
          select 1
          from public.news_story_articles members
          where members.article_id = articles.id
        )
      union all
      select 'story'::text as entry_kind, stories.id as entry_id, stories.published_at
      from public.news_stories stories
      where stories.status = 'published'
    $view$;
  end if;
end;
$$;

alter table public.news_dedup_locks enable row level security;
alter table public.news_dedup_decisions enable row level security;

drop policy if exists "Admins can read news dedup decisions" on public.news_dedup_decisions;
create policy "Admins can read news dedup decisions" on public.news_dedup_decisions
for select to authenticated using (public.is_admin());

drop policy if exists "Public can read published articles" on public.news_articles;
create policy "Public can read published articles" on public.news_articles
for select to anon, authenticated
using (
  status = 'processed'
  and publication_status = 'published'
  and duplicate_of is null
);

create or replace function public.acquire_news_dedup_lock(
  p_lock_key text,
  p_article_id uuid,
  p_stale_after_seconds integer default 300
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.news_dedup_locks (
    lock_key,
    article_id,
    acquired_at,
    expires_at
  )
  values (
    p_lock_key,
    p_article_id,
    now(),
    now() + make_interval(secs => greatest(30, least(coalesce(p_stale_after_seconds, 300), 1800)))
  )
  on conflict (lock_key) do update
  set
    article_id = excluded.article_id,
    acquired_at = excluded.acquired_at,
    expires_at = excluded.expires_at
  where
    public.news_dedup_locks.expires_at <= now()
    or public.news_dedup_locks.article_id = excluded.article_id;

  return found;
end;
$$;

create or replace function public.release_news_dedup_lock(
  p_lock_key text,
  p_article_id uuid
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.news_dedup_locks
  where lock_key = p_lock_key
    and article_id = p_article_id;

  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$$;

revoke all on table public.news_dedup_locks from public, anon, authenticated;
revoke all on table public.news_dedup_decisions from public, anon, authenticated;
revoke all on sequence public.news_dedup_decisions_id_seq from public, anon, authenticated;
revoke all on function public.acquire_news_dedup_lock(text, uuid, integer) from public, anon, authenticated;
revoke all on function public.release_news_dedup_lock(text, uuid) from public, anon, authenticated;

grant select on table public.news_dedup_decisions to authenticated;
grant select, insert, update, delete on table public.news_dedup_locks to service_role;
grant select, insert, update, delete on table public.news_dedup_decisions to service_role;
grant usage, select on sequence public.news_dedup_decisions_id_seq to service_role;
grant execute on function public.acquire_news_dedup_lock(text, uuid, integer) to service_role;
grant execute on function public.release_news_dedup_lock(text, uuid) to service_role;
